language: generic

sudo: required

services:
  - docker

before_install:
  - docker buildx build  -t smileajw1004/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true smileajw1004/react-test-app npm test

after_success:
  - docker build -t hiwbaski/thisisnevercode-frontend ./frontend
  - docker build -t hwibaski/thisisnevercode-backend ./backend

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hwibaski/thisisnevercode-frontend
  - docker push hwibaski/thisisnevercode-backend
# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-northeast-2'
#   app: 'docker-fullstack-app'
#   env: 'DockerFullstackApp-env'
#   bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
#   bucket_path: 'docker-fullstack-app'
#   on:
#     branch: master

#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
