language: generic

sudo: required

services:
  - docker

after_success:
  - docker build -t hwibaski/thisisnevercode-frontend ./frontend
  - docker build -t hwibaski/thisisnevercode-backend ./backend

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push hwibaski/thisisnevercode-frontend
  - docker push hwibaski/thisisnevercode-backend
