version: '3'
services:
  frontend:
    image: hwibaski/thisisnevercode-frontend
    ports:
      - '3000:3000'
    stdin_open: true

  backend:
    image: hwibaski/thisisnevercode-backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - JWT_SECRET=super secret key
      - JWT_TTL=super salt
      - SALT=super salt
      - ACCESS_TOKEN_SECRET_KEY=b8f3824686de0192a583641a6416d9975941129bc028bdf4665014795f91c26b92835dcc81b7d855fd4d161146ea33a65e69559238acabb99a29b4d93c1c442
      - DATABASE_URL=mysql://root:Gnlqktmzl12@hwibaski-mysql.csckotwfrcog.ap-northeast-2.rds.amazonaws.com:3306/thisisnevercode
