version: '3'
services:
  frontend:
    image: hwibaski/thisisnevercode-frontend
    ports:
      - 3000:3000
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    mem_limit: 128m

  backend:
    image: hwibaski/thisisnevercode-backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TTL=${JWT_TTL}
      - SALT=${SALT}
      - ACCES_TOKEN_SECRET_KEY=${ACCES_TOKEN_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    mem_limit: 128m
