version: '3'
services:
  frontend:
    image: hwibaski/thisisnevercode-frontend
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: hwibaski/docker-nginx
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: hwibaski/thisisnevercode-backend
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_TTL=${JWT_TTL}
      - SALT=${SALT}
      - ACCES_TOKEN_SECRET_KEY=${ACCES_TOKEN_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
    mem_limit: 128m
